[2025-03-09T04:23:43.392+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-09T04:23:43.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-03-09T04:23:43.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-03-09T04:23:43.425+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2025-03-09T04:23:43.439+0000] {taskinstance.py:2330} INFO - Executing <Task(SSHOperator): submit_spark_via_ssh> on 2025-03-07 00:00:00+00:00
[2025-03-09T04:23:43.445+0000] {standard_task_runner.py:63} INFO - Started process 5276 to run task
[2025-03-09T04:23:43.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'submit_spark_job_v2', 'submit_spark_via_ssh', 'scheduled__2025-03-07T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/match_info_spark_process_v2.py', '--cfg-path', '/tmp/tmpwqehto5o']
[2025-03-09T04:23:43.452+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask submit_spark_via_ssh
[2025-03-09T04:23:43.519+0000] {task_command.py:426} INFO - Running <TaskInstance: submit_spark_job_v2.submit_spark_via_ssh scheduled__2025-03-07T00:00:00+00:00 [running]> on host 40942f81e2c9
[2025-03-09T04:23:43.638+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='submit_spark_job_v2' AIRFLOW_CTX_TASK_ID='submit_spark_via_ssh' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T00:00:00+00:00'
[2025-03-09T04:23:43.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-09T04:23:43.655+0000] {ssh.py:151} INFO - Creating ssh_client
[2025-03-09T04:23:43.655+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-09T04:23:43.670+0000] {base.py:84} INFO - Using connection ID 'spark_ssh_conn' for task execution.
[2025-03-09T04:23:43.671+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-09T04:23:43.677+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-09T04:23:43.688+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 1
[2025-03-09T04:23:46.752+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-09T04:23:46.760+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 2
[2025-03-09T04:23:50.180+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-09T04:23:50.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-09T04:23:50.188+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in get_ssh_client
    return self.hook.get_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/hooks/ssh.py", line 347, in get_conn
    for attempt in Retrying(
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/hooks/ssh.py", line 354, in get_conn
    client.connect(**connect_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/pkey.py", line 421, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/rsakey.py", line 196, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/pkey.py", line 494, in _read_private_key_file
    with open(filename, "r") as f:
PermissionError: [Errno 13] Permission denied: '/opt/airflow/plugins/programmers-fc-key.pem'
[2025-03-09T04:23:50.206+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=submit_spark_job_v2, task_id=submit_spark_via_ssh, run_id=scheduled__2025-03-07T00:00:00+00:00, execution_date=20250307T000000, start_date=20250309T042343, end_date=20250309T042350
[2025-03-09T04:23:50.235+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task submit_spark_via_ssh ([Errno 13] Permission denied: '/opt/airflow/plugins/programmers-fc-key.pem'; 5276)
[2025-03-09T04:23:50.250+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-09T04:23:50.271+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T04:23:50.274+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
