[2025-03-08T03:18:17.531+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-08T03:18:17.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 scheduled__2025-03-07T01:00:00+00:00 [queued]>
[2025-03-08T03:18:17.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 scheduled__2025-03-07T01:00:00+00:00 [queued]>
[2025-03-08T03:18:17.583+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-08T03:18:17.753+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_and_save_match_data_to_json_to_s3> on 2025-03-07 01:00:00+00:00
[2025-03-08T03:18:17.760+0000] {standard_task_runner.py:63} INFO - Started process 1804 to run task
[2025-03-08T03:18:17.764+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_nexon_data_sequential', 'collect_and_save_match_data_to_json_to_s3', 'scheduled__2025-03-07T01:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/collect_match_info.py', '--cfg-path', '/tmp/tmpi9lkf77s']
[2025-03-08T03:18:17.766+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask collect_and_save_match_data_to_json_to_s3
[2025-03-08T03:18:17.832+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 scheduled__2025-03-07T01:00:00+00:00 [running]> on host be828dc9717c
[2025-03-08T03:18:17.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_nexon_data_sequential' AIRFLOW_CTX_TASK_ID='collect_and_save_match_data_to_json_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T01:00:00+00:00'
[2025-03-08T03:18:17.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-08T03:18:17.961+0000] {collect_match_info.py:125} INFO - Collecting 2025-03-08's data
[2025-03-08T03:18:18.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-08T03:18:18.188+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/collect_match_info.py", line 134, in process_data
    obj = s3.get_object(Bucket=S3_BUCKET, Key=S3_KEY_CRAWL_PREFIX)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-08T03:18:18.203+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_nexon_data_sequential, task_id=collect_and_save_match_data_to_json_to_s3, run_id=scheduled__2025-03-07T01:00:00+00:00, execution_date=20250307T010000, start_date=20250308T031817, end_date=20250308T031818
[2025-03-08T03:18:18.216+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task collect_and_save_match_data_to_json_to_s3 (An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.; 1804)
[2025-03-08T03:18:18.260+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-08T03:18:18.284+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T03:18:18.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
