[2025-03-12T01:33:08.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-12T01:33:08.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_to_redshift.s3_to_redshift_match_trend_data scheduled__2025-03-11T01:30:00+00:00 [queued]>
[2025-03-12T01:33:08.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_to_redshift.s3_to_redshift_match_trend_data scheduled__2025-03-11T01:30:00+00:00 [queued]>
[2025-03-12T01:33:08.553+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-12T01:33:08.567+0000] {taskinstance.py:2330} INFO - Executing <Task(S3ToRedshiftOperator): s3_to_redshift_match_trend_data> on 2025-03-11 01:30:00+00:00
[2025-03-12T01:33:08.574+0000] {standard_task_runner.py:63} INFO - Started process 3839 to run task
[2025-03-12T01:33:08.579+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parquet_to_redshift', 's3_to_redshift_match_trend_data', 'scheduled__2025-03-11T01:30:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/match_info_redshift_dag.py', '--cfg-path', '/tmp/tmpe2gsg3sn']
[2025-03-12T01:33:08.581+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask s3_to_redshift_match_trend_data
[2025-03-12T01:33:08.650+0000] {task_command.py:426} INFO - Running <TaskInstance: parquet_to_redshift.s3_to_redshift_match_trend_data scheduled__2025-03-11T01:30:00+00:00 [running]> on host a0d797a25898
[2025-03-12T01:33:08.774+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parquet_to_redshift' AIRFLOW_CTX_TASK_ID='s3_to_redshift_match_trend_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T01:30:00+00:00'
[2025-03-12T01:33:08.775+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-12T01:33:08.806+0000] {base.py:84} INFO - Using connection ID 's3_conn_team' for task execution.
[2025-03-12T01:33:08.818+0000] {base.py:84} INFO - Using connection ID 's3_conn_team' for task execution.
[2025-03-12T01:33:08.820+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_conn_team', conn_type='aws') credentials retrieved from login and password.
[2025-03-12T01:33:08.832+0000] {s3_to_redshift.py:193} INFO - Executing COPY command...
[2025-03-12T01:33:08.847+0000] {base.py:84} INFO - Using connection ID 'redshift_conn_team' for task execution.
[2025-03-12T01:33:09.204+0000] {sql.py:470} INFO - Running statement: CREATE TABLE #match_info (LIKE trend_analytics.match_info INCLUDING DEFAULTS);, parameters: None
[2025-03-12T01:33:09.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-12T01:33:09.212+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/redshift_connector/core.py", line 1821, in execute
    ps = cache["ps"][key]
KeyError: ('CREATE TABLE #match_info (LIKE trend_analytics.match_info INCLUDING DEFAULTS);', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 197, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.9/site-packages/redshift_connector/core.py", line 1902, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.9/site-packages/redshift_connector/core.py", line 2194, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42P01', 'M': 'relation "trend_analytics" does not exist', 'F': '/opt/brazil-pkg-cache/packages/RedshiftPADB/RedshiftPADB-1.0.8470.0/AL2_x86_64/generic-flavor/src/src/pg/src/backend/catalog/namespace.c', 'L': '259', 'R': 'LocalRangeVarGetRelid'}
[2025-03-12T01:33:09.234+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parquet_to_redshift, task_id=s3_to_redshift_match_trend_data, run_id=scheduled__2025-03-11T01:30:00+00:00, execution_date=20250311T013000, start_date=20250312T013308, end_date=20250312T013309
[2025-03-12T01:33:09.251+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 71 for task s3_to_redshift_match_trend_data ({'S': 'ERROR', 'C': '42P01', 'M': 'relation "trend_analytics" does not exist', 'F': '/opt/brazil-pkg-cache/packages/RedshiftPADB/RedshiftPADB-1.0.8470.0/AL2_x86_64/generic-flavor/src/src/pg/src/backend/catalog/namespace.c', 'L': '259', 'R': 'LocalRangeVarGetRelid'}; 3839)
[2025-03-12T01:33:09.274+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-12T01:33:09.298+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T01:33:09.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
