[2025-03-08T08:02:26.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-08T08:02:26.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [queued]>
[2025-03-08T08:02:26.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [queued]>
[2025-03-08T08:02:26.692+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-08T08:02:26.706+0000] {taskinstance.py:2330} INFO - Executing <Task(SSHOperator): submit_spark_via_ssh> on 2025-03-08 08:02:25.697911+00:00
[2025-03-08T08:02:26.714+0000] {standard_task_runner.py:63} INFO - Started process 10896 to run task
[2025-03-08T08:02:26.721+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'submit_spark_job_v2', 'submit_spark_via_ssh', 'manual__2025-03-08T08:02:25.697911+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/match_info_spark_process_v2.py', '--cfg-path', '/tmp/tmpvf8k1sly']
[2025-03-08T08:02:26.724+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask submit_spark_via_ssh
[2025-03-08T08:02:26.796+0000] {task_command.py:426} INFO - Running <TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [running]> on host be828dc9717c
[2025-03-08T08:02:26.872+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'submit_spark_via_ssh', field 'command'. Template: '\n    set -e  # 명령어 실패 시 즉시 종료\n    echo "Starting Spark Job on {{ params.spark_server }}"\n\n    ssh -i {{ params.pem_file }} ubuntu@{{ params.spark_server }} << \'EOF\'\n    echo "Submitting Spark Job..."\n    spark-submit {{ params.spark_script }} --processing_date {{ data_interval_end | ds }} > spark_job.log 2>&1\n    exit_code=$?\n\n    # 실행 로그 출력 (Airflow에서 확인 가능)\n    cat spark_job.log\n\n    # Spark 실패 감지\n    if [ $exit_code -ne 0 ]; then\n        echo "Spark Job Failed! Check logs."\n        exit 1\n    else\n        echo "Spark Job Succeeded!"\n    fi\n    EOF\n    '
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 22, in root
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'pem_file'
[2025-03-08T08:02:26.880+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 22, in root
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'pem_file'
[2025-03-08T08:02:26.893+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=submit_spark_job_v2, task_id=submit_spark_via_ssh, run_id=manual__2025-03-08T08:02:25.697911+00:00, execution_date=20250308T080225, start_date=20250308T080226, end_date=20250308T080226
[2025-03-08T08:02:26.913+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task submit_spark_via_ssh ('dict object' has no attribute 'pem_file'; 10896)
[2025-03-08T08:02:26.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-08T08:02:26.961+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T08:02:26.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
