[2025-03-08T08:20:45.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-08T08:20:45.040+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [queued]>
[2025-03-08T08:20:45.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [queued]>
[2025-03-08T08:20:45.049+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-03-08T08:20:45.064+0000] {taskinstance.py:2330} INFO - Executing <Task(SSHOperator): submit_spark_via_ssh> on 2025-03-08 08:02:25.697911+00:00
[2025-03-08T08:20:45.070+0000] {standard_task_runner.py:63} INFO - Started process 11515 to run task
[2025-03-08T08:20:45.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'submit_spark_job_v2', 'submit_spark_via_ssh', 'manual__2025-03-08T08:02:25.697911+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/match_info_spark_process_v2.py', '--cfg-path', '/tmp/tmpwu07uecn']
[2025-03-08T08:20:45.077+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask submit_spark_via_ssh
[2025-03-08T08:20:45.148+0000] {task_command.py:426} INFO - Running <TaskInstance: submit_spark_job_v2.submit_spark_via_ssh manual__2025-03-08T08:02:25.697911+00:00 [running]> on host be828dc9717c
[2025-03-08T08:20:45.264+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='submit_spark_job_v2' AIRFLOW_CTX_TASK_ID='submit_spark_via_ssh' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T08:02:25.697911+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T08:02:25.697911+00:00'
[2025-03-08T08:20:45.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-08T08:20:45.281+0000] {ssh.py:151} INFO - Creating ssh_client
[2025-03-08T08:20:45.281+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-08T08:20:45.296+0000] {base.py:84} INFO - Using connection ID 'spark_ssh_conn' for task execution.
[2025-03-08T08:20:45.297+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-08T08:20:45.301+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-08T08:20:45.312+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 1
[2025-03-08T08:20:48.791+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-08T08:20:48.800+0000] {ssh.py:343} INFO - Failed to connect. Sleeping before retry attempt 2
[2025-03-08T08:20:53.038+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-08T08:20:53.086+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-08T08:20:53.087+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in get_ssh_client
    return self.hook.get_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/hooks/ssh.py", line 347, in get_conn
    for attempt in Retrying(
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/ssh/hooks/ssh.py", line 354, in get_conn
    client.connect(**connect_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/airflow/.local/lib/python3.9/site-packages/paramiko/client.py", line 819, in _auth
    raise SSHException("No authentication methods available")
paramiko.ssh_exception.SSHException: No authentication methods available
[2025-03-08T08:20:53.102+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=submit_spark_job_v2, task_id=submit_spark_via_ssh, run_id=manual__2025-03-08T08:02:25.697911+00:00, execution_date=20250308T080225, start_date=20250308T082045, end_date=20250308T082053
[2025-03-08T08:20:53.115+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task submit_spark_via_ssh (No authentication methods available; 11515)
[2025-03-08T08:20:53.124+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-08T08:20:53.146+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T08:20:53.148+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
