[2025-03-08T03:12:41.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-08T03:12:41.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 manual__2025-03-08T03:12:39.952065+00:00 [queued]>
[2025-03-08T03:12:41.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 manual__2025-03-08T03:12:39.952065+00:00 [queued]>
[2025-03-08T03:12:41.792+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-08T03:12:41.962+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_and_save_match_data_to_json_to_s3> on 2025-03-08 03:12:39.952065+00:00
[2025-03-08T03:12:41.969+0000] {standard_task_runner.py:63} INFO - Started process 1625 to run task
[2025-03-08T03:12:41.973+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_nexon_data_sequential', 'collect_and_save_match_data_to_json_to_s3', 'manual__2025-03-08T03:12:39.952065+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/collect_match_info.py', '--cfg-path', '/tmp/tmpri3vychq']
[2025-03-08T03:12:41.975+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask collect_and_save_match_data_to_json_to_s3
[2025-03-08T03:12:42.041+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_nexon_data_sequential.collect_and_save_match_data_to_json_to_s3 manual__2025-03-08T03:12:39.952065+00:00 [running]> on host be828dc9717c
[2025-03-08T03:12:42.170+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_nexon_data_sequential' AIRFLOW_CTX_TASK_ID='collect_and_save_match_data_to_json_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T03:12:39.952065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T03:12:39.952065+00:00'
[2025-03-08T03:12:42.171+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-08T03:12:42.216+0000] {collect_match_info.py:125} INFO - Collecting 2025-03-08's data
[2025-03-08T03:12:42.968+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-08T03:12:42.968+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/collect_match_info.py", line 134, in process_data
    obj = s3.get_object(Bucket=S3_BUCKET, Key=S3_KEY_CRAWL_PREFIX)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-08T03:12:42.985+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_nexon_data_sequential, task_id=collect_and_save_match_data_to_json_to_s3, run_id=manual__2025-03-08T03:12:39.952065+00:00, execution_date=20250308T031239, start_date=20250308T031241, end_date=20250308T031242
[2025-03-08T03:12:43.001+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task collect_and_save_match_data_to_json_to_s3 (An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.; 1625)
[2025-03-08T03:12:43.028+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-08T03:12:43.053+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T03:12:43.055+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
